language: objective-c
osx_image: xcode10.2
script:
  - xcodebuild test -project Travis-Sample.xcodeproj -scheme Travis-Sample. -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO